require 'namespacing'

module App
	class Entity < Sequel::Model
		# = Entity
		#
		# The base Entity model, used by NiftyVM
		#
		# * Entities used the InheritanceMixin for STI
		# * Entity's subclasses are generated by the EntityKind model on Schema load
		#
		#
		# = Architecture
		# *	Entity 
		#    + Fields
		# 	 + Fieldlets	
		#
		# == Fields
		# A Field is a set of 1 or more instances, and a solid definition of it's fieldlets
		# 	Every FieldInstnace has the Fieldlets acording to the definition in the field
		#
		# == Fieldlets
		# Fieldlet is the smallest piece of information that can be store in an entity
		# Simple examples of fieldlets are: String, Text, File, Date etc
		# 
		# For more information about entities, checkout entity's included modules
		
			
		# set schema
		set_schema(:entities) do 
			bigint		  :id, :unsigned => true, :null => false
			bigint			:kind, :unsigned => true, :null => false
			timestamp		:created_at
			timestamp		:updated_at
			varchar			:display

			primary_key [:id]
			index				[:display,:kind]
		end
		
		# Inheritance Mixin - for smart STI
		include InheritanceMixin
		include Namespacing
		
		# setup all the instance variables
		after_initialize do 
			@fieldlets = Hash.new{|hash, key| hash[key] = {}}
			@fields = FieldContainer.new(self.class::FIELDS)
			@instances = {}
			@fieldlets_by_type = {}
		end
		
	end
end