# must load namespaces
require 'namespaces'
require 'inheritance_mixin'


module App
	class Entity < Sequel::Model
		# = Entity
		#
		# The base Entity model, used by NiftyVM
		#
		# * Entities used the InheritanceMixin for STI
		# * Entity's subclasses are generated by the EntityKind model on Schema load
		#
		#
		# = Architecture
		# *	Entity 
		#    + Fields
		# 	 + Fieldlets	
		#
		# == Fields
		# A Field is a set of 1 or more instances, and a solid definition of it's fieldlets
		# 	Every FieldInstnace has the Fieldlets acording to the definition in the field
		#
		# == Fieldlets
		# Fieldlet is the smallest piece of information that can be store in an entity
		# Simple examples of fieldlets are: String, Text, File, Date etc
		# 
		# For more information about entities, checkout entity's included modules
		
			
		# set schema
		set_schema(:entities) do 
			primary_key :id, :unsigned => true
			varchar			:kind, :size => 32
			datetime		:created_at
			datetime		:updated_at
			varchar			:display

			index				[:kind, :display]
			index				[:display]
		end
		
		# Inheritance Mixin - for smart STI
		include InheritanceMixin
		
	end
end