# class for field

# this class is generated by the FieldKind
# instance is intitalized 
#
module App
	class Field
		def initialize(entity)
			@entity = entity
			@fieldlets = entity.fieldlets.fieldlets.reject do |key,value| 
				not self.class.fieldlet_kind_ids.include?(key)
			end
		end
		
		def fieldlets
			@fieldlets
		end
		
		def instances
			@instances = {}
			@fieldlets.values.each do |hash|
				hash.each do |key,value|
					@instances[key] ||= []
					@instances[key] << value
				end
			end
			
			return @instances
		end
	end
end