---
# This is a sample database file for the Sequel ORM
:development: &defaults
  :adapter: mysql
  :database: niftykm_development
  :username: root
  :password: 
  :host: localhost
  :port: 3306

:test:
  <<: *defaults
  :database: niftykm_testing
  
:debug:
  <<: *defaults
  

:production:
  <<: *defaults
  :database: niftykm_development